spring.application.name=LoginApp
 
server.port=8080

spring.data.mongodb.uri=mongodb+srv://myAtlasDBUser:1234@myatlasclusteredu.wspjy.mongodb.net/login?retryWrites=true&w=majority&appName=myAtlasClusterEDU


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
